# Generated by Django 4.0.3 on 2022-03-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactnumber', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('cust', models.CharField(choices=[('JEWELRY', 'jewelry'), ('LAND', 'land'), ('VEHICLES', 'vehicles')], max_length=100)),
            ],
        ),
    ]
